cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    Teste:
      email: Teste@teste
      name: Teste
      password: $2b$12$vdQ367lx3j//NHzXbTd1R.uU01et4KZMzZHGZt8Ei.SXRDYrY9Sqe
